

  const firebaseConfig = {
    apiKey: "AIzaSyAfMMWFTbavWyBG1dwzz1fqy0m-Fhdu_Y0",
    authDomain: "hrd-130b9.firebaseapp.com",
    projectId: "hrd-130b9",
    storageBucket: "hrd-130b9.firebasestorage.app",
    messagingSenderId: "112571754580",
    appId: "1:112571754580:web:cb03d46faa3baf59b7e5c1",
    measurementId: "G-5Q13B409F6"
  
